### ISSUE TITLE
Invalid customer ID

### ISSUE THREAD

**Issue by MitulGedeeya** [Opteo/google-ads-api#312] opened 2021-08-05 20:08 UTC
Started getting this error. I tried multiple ads Id but it always gives me same error 

```
GoogleAdsFailure {
  errors: [
    GoogleAdsError {
      error_code: [ErrorCode],
      message: "Invalid customer ID ''."
    }
  ],
  request_id: '5qJwTFD3XIuWfJKCXNfonw'
}
```

My Function to create client is as follow

```
auth(adsId) {
    adsId = adsId.replace(/-/g, '')

    try {
      return client.Customer({
        customer_id: adsId,
        login_customer_id: 'xxxxxxxxx', // Optionally provide a login-customer-id
        refresh_token: constants.refreshToken
      })
    } catch (exception) {
      utils.throwError(500, '', 'Error creating Ads auth')(exception)
    }
  }
```

**Comment by MitulGedeeya** [comment] 2021-08-06 05:26
@WillCooter I investigated this issue. It seems issue started from 8.0.0. When I move back to 5.2.0 it works perfectly.

**Comment by jfcorsini** [comment] 2021-08-09 06:22
I am currently running the version 8.0.1 of google-ads-api and was not having this issue at all. Today my CI bumped the version of google-ads-node from 6.0.0 to 6.1.2 and then we started having this error of `Invalid customer ID ''.` as well, so it might be related to this other library.

**Comment by arditti** [comment] 2021-08-09 16:54
Same here. since the update to version `8.0.2` we encounter with this issue. rolled back to version 5.0.2

**Comment by matcwhite** [comment] 2021-08-12 14:43
I'm also having this issue. I've just upgraded from v5 to v8.0.1 and have started getting this `Invalid customer ID ''.` error.
```javascript
const client = new GoogleAdsApi({
	client_id:			process.env.GAW_CLIENT_ID,
	client_secret:		process.env.GAW_CLIENT_SECRET,
	developer_token:	process.env.GAW_DEVELOPER_TOKEN
});

const customer = client.Customer({
	customer_id:		process.env.GAW_CUSTOMER_ID,
	refresh_token:	process.env.GAW_REFRESH_TOKEN,
});

const campaigns = await customer.report({
	entity: "campaign",
	attributes: [
		"campaign.id",
		"campaign.name"
	 ]
});

console.log(campaigns);
```
This worked fine with version v5. with v8.0.1:
```javascript
GoogleAdsFailure {
  errors: [
    GoogleAdsError {
      error_code: [ErrorCode],
      message: "Invalid customer ID ''."
    }
  ],
  request_id: 'QxlpOgZoWqzcCxJxxTOfVg'
}
```

**Comment by MitulGedeeya** [comment] 2021-08-13 04:17
> I'm also having this issue. I've just upgraded from v5 to v8.0.1 and have started getting this `Invalid customer ID ''.` error.
> 
> ```js
> const client = new GoogleAdsApi({
> 	client_id:		process.env.GAW_CLIENT_ID,
> 	client_secret:		process.env.GAW_CLIENT_SECRET,
> 	developer_token:	process.env.GAW_DEVELOPER_TOKEN
> });
> 
> const customer = client.Customer({
> 	customer_id:	process.env.GAW_CUSTOMER_ID,
> 	refresh_token:	process.env.GAW_REFRESH_TOKEN,
> });
> 
> const campaigns = await customer.report({
> 	entity: "campaign",
> 	attributes: [
> 		"campaign.id",
> 		"campaign.name"
> 	 ]
> });
> 
> console.log(campaigns);
> ```
> 
> This worked fine with version v5. with v8.0.1:
> 
> ```js
> GoogleAdsFailure {
>   errors: [
>     GoogleAdsError {
>       error_code: [ErrorCode],
>       message: "Invalid customer ID ''."
>     }
>   ],
>   request_id: 'QxlpOgZoWqzcCxJxxTOfVg'
> }
> ```
> 
> I am definitely specifying the Customer ID with only numbers, no hyphens, e.g. '1234567890'.

Have you tried version `5.0.2` ?

**Comment by matcwhite** [comment] 2021-08-13 08:23
Yep it works on`5.0.2`. I upgraded to `8.0.1` in an attempt to resolve other problems. Could somebody confirm exactly which version the documentation is for? Although my understanding is that there are a lot of issues with older versions because of changes at Google's end.

**Comment by MitulGedeeya** [comment] 2021-08-15 14:44
I made changes by forking library temporary until they fix issue. There were 2 or 3 issues which j fixed.

**Comment by cyruszah** [comment] 2021-08-16 23:21
Is there a fix or a workaround for this issue yet, wee need to migrate to v8 of the API and this is breaking our code?

**Comment by varun27896** [comment] 2021-08-18 02:20
I had issues with `8.0.0` onwards with `listAccessibleCustomers` method. It returns an empty array with `8.0.0`+ but returns the expected array of customer objects when I install the older version i.e `5.2.0`/`5.1.3`. Hope they fix this in their next patch release

**Comment by WillCooter** [comment] 2021-08-23 12:07
Hi all, apologies for the delayed response. We are aware of this issue and are communicating with Google to get it solved. It seems something went wrong in the latest builds. I will post here again when we have a solution

**Comment by WillCooter** [comment] 2021-09-06 12:40
@MitulGedeeya @jfcorsini @arditti @matcwhite @cyruszah @varun27896 The invalid customer id issue should be fixed with the latest version of the library (v8.1.0)

**Comment by arditti** [comment] 2021-09-06 12:42
> @MitulGedeeya @jfcorsini @arditti @matcwhite @cyruszah @varun27896 The invalid customer id issue should be fixed with the latest version of the library (v8.1.0)

Amazing, I'll test it shortly. Appreciate the effort here

**Comment by meip** [comment] 2021-09-06 13:36
@WillCooter great job! I can confirm the fix in v8.1.0. Thank you!

**Comment by jgartor** [comment] 2021-09-06 13:43
I can confirm this is working in v8.1.0 as well! Thank you!

**Closed** 2021-09-06 16:56 UTC
Labels: bug :warning:

**Comment by kortemy** [comment] 2021-10-08 13:27
@WillCooter Sorry to necro this, but I am getting this error even with 8.1.0.

Literally the same basic use case hen listing campaigns.

```
   const account_id = '123-456-7890'
   const client = new Ads.GoogleAdsApi({
      client_id: AdsConfig.client.id, //'<YOUR_CLIENT_ID>',
      client_secret: AdsConfig.client.secret, //'<YOUR_CLIENT_SECRET>',
      developer_token: AdsConfig.developerToken, //'<YOUR_DEVELOPER_TOKEN>',
    })
    const customer = client.Customer({
      customer_account_id: account_id, // target customer client id
      login_customer_id: AdsConfig.customerId, // MCC client id
      refresh_token: AdsTokens.refresh_token, //'<YOUR_REFRESH_TOKEN>',
    })
    const query = {
      entity: 'campaign',
      attributes: [
        'campaign.id',
        'campaign.name',
        'campaign.status',
        'campaign.tracking_url_template'
      ],
      constraints: [
        { key: 'campaign.status', op: '!=', val: Ads.enums.CampaignStatus.REMOVED }
      ]
    }
    const result = await customer.report(query)
    console.log(result)

```

Same error message:

```
GoogleAdsFailure {
  errors: [
    GoogleAdsError {
      error_code: [ErrorCode],
      message: "Invalid customer ID ''."
    }
  ],
  request_id: 'U_rBJ9oX3tdKtww8lhzCeA'
}
```

And yes, I am accessing account via MCC, but I am getting the same error even when accessing account directly.

Any ideas?
